name: Run Stock Data Script

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # The correct checkout action syntax

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # Adjust as needed

      - name: Install dependencies
        run: |
          pip install pandas nselib google-api-python-client google-auth-httplib2 google-auth-oauthlib google-auth requests python-dateutil

      - name: Create gdrive.json file from secret
        run: |
          echo "${{ secrets.GDRIVE_JSON }}" > gdrive.json
        shell: bash

      - name: Run script
        run: |
          python see.py
        
      - name: Upload results to GitHub as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: stock-data
          path: stock_data.csv

      - name: Cleanup
        run: rm -f gdrive.json
