name: Run Stock Data Script

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Adjust as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas==2.2.2
          pip install nselib==1.0
          pip install google-api-python-client==2.145.0
          pip install google-auth-httplib2==0.2.0
          pip install google-auth-oauthlib==1.2.1
          pip install github==1.2.7
          pip install pyasn1-modules==0.4.1
          pip install pyasn1==0.6.1

      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python see.py

      - name: Upload output to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: output-file
          path: stock_data.csv  # Update with the path to your output file

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: CoderMikhael
          author_email: kbp232@gmail.com
          message: 'Update output file'
          add: 'stock_data.csv'
