name: Run Stock Data Script

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight UTC every day
  workflow_dispatch: # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install pandas requests
          pip install nselib # Install other dependencies as required

      - name: Run Stock Data Script
        run: |
          python see.py

      - name: Upload CSV to Repository
        uses: actions/upload-artifact@v3
        with:
          name: stock-data
          path: stock_data.csv
